services:
  backend:
    build:
      context: .
    networks:
      - ianalyzer-network
    volumes:
      - type: bind
        source: ./code
        target: /backend/code
    environment:
      ES_HOST: $ES_HOST

networks:
  ianalyzer-network:
    name: $NETWORK
    external: true