services:
  backend:
    build:
      context: .
    networks:
      - ianalyzer-network
    volumes:
      - type: bind
        source: ./code
        target: /backend/code
      - type: bind
        source: $DATA_DIR
        target: /backend/data
    environment:
      ES_HOST: $ES_HOST

networks:
  ianalyzer-network:
    name: $NETWORK
    external: true